# Generated by Django 3.1 on 2020-08-09 13:53

from django.db import migrations, models
import django.db.models.deletion
import store.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(max_length=999)),
                ('date_version', models.DateField(auto_now_add=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to=store.models._new_image_path)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'ordering': ('-date_version', 'name'),
            },
        ),
    ]
