# Generated by Django 3.1 on 2020-08-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200825_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='12345', max_length=20),
            preserve_default=False,
        ),
    ]
